import {
  ArrowRight,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  Github,
  Globe,
  Heart,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboard,
  Loader2,
  LucideIcon,
  MessageCircle,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Settings2,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Trash,
  TrendingUp,
  Twitter,
  User,
  X,
  Zap,
  Linkedin,
  Menu,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: HelpCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  check: Check,
  calendar: Calendar,
  messageCircle: MessageCircle,
  heart: Heart,
  trendingUp: TrendingUp,
  globe: Globe,
  smartphone: Smartphone,
  sparkles: Sparkles,
  zap: Zap,
  settings2: Settings2,
  linkedin: Linkedin,
  star: Star,
  dashboard: LayoutDashboard,
  menu: Menu,
};
